-- Huella de datos (M1): recuento + md5 de columnas originales. Debe coincidir antes/después.
select string_agg(t||':'||c||':'||h, E'\n' order by t) from (
select 'assets' t,(select count(*) from public.assets) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.assets x) h
union all select 'locations' t,(select count(*) from public.locations) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.locations x) h
union all select 'maintenance_plans' t,(select count(*) from public.maintenance_plans) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.maintenance_plans x) h
union all select 'maintenance_sessions' t,(select count(*) from public.maintenance_sessions) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.maintenance_sessions x) h
union all select 'checklist_templates' t,(select count(*) from public.checklist_templates) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.checklist_templates x) h
union all select 'incidents' t,(select count(*) from public.incidents) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.incidents x) h
union all select 'certificates' t,(select count(*) from public.certificates) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.certificates x) h
union all select 'certificate_templates' t,(select count(*) from public.certificate_templates) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.certificate_templates x) h
union all select 'vehicles' t,(select count(*) from public.vehicles) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.vehicles x) h
union all select 'asset_types' t,(select count(*) from public.asset_types) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.asset_types x) h
union all select 'asset_families' t,(select count(*) from public.asset_families) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.asset_families x) h
union all select 'companies' t,(select count(*) from public.companies) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.companies x) h
union all select 'company_members' t,(select count(*) from public.company_members) c,(select md5(coalesce(string_agg((to_jsonb(x))::text,'' order by (to_jsonb(x))::text),'')) from public.company_members x) h
union all select 'checklist_template_versions' t,(select count(*) from public.checklist_template_versions) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.checklist_template_versions x) h
union all select 'checklist_questions' t,(select count(*) from public.checklist_questions) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.checklist_questions x) h
union all select 'checklist_responses' t,(select count(*) from public.checklist_responses) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.checklist_responses x) h
union all select 'maintenance_items' t,(select count(*) from public.maintenance_items) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.maintenance_items x) h
union all select 'maintenance_plan_assets' t,(select count(*) from public.maintenance_plan_assets) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.maintenance_plan_assets x) h
union all select 'maintenance_plan_type_templates' t,(select count(*) from public.maintenance_plan_type_templates) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.maintenance_plan_type_templates x) h
union all select 'certificate_items' t,(select count(*) from public.certificate_items) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.certificate_items x) h
union all select 'incident_status_history' t,(select count(*) from public.incident_status_history) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.incident_status_history x) h
union all select 'session_reopen_log' t,(select count(*) from public.session_reopen_log) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.session_reopen_log x) h
union all select 'first_aid_kit_contents' t,(select count(*) from public.first_aid_kit_contents) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.first_aid_kit_contents x) h
union all select 'vehicle_mounts' t,(select count(*) from public.vehicle_mounts) c,(select md5(coalesce(string_agg((to_jsonb(x) - 'company_id')::text,'' order by (to_jsonb(x) - 'company_id')::text),'')) from public.vehicle_mounts x) h
) s;
