/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrTokenRouteImport } from './routes/qr.$token'
import { Route as AuthenticatedSelectCompanyRouteImport } from './routes/_authenticated/select-company'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingCompanyRouteImport } from './routes/_authenticated/onboarding.company'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app.settings'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app.notifications'
import { Route as AuthenticatedAppMaintenancePlansRouteImport } from './routes/_authenticated/_app.maintenance-plans'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/_app.maintenance'
import { Route as AuthenticatedAppLocationsRouteImport } from './routes/_authenticated/_app.locations'
import { Route as AuthenticatedAppIncidentsRouteImport } from './routes/_authenticated/_app.incidents'
import { Route as AuthenticatedAppImportsRouteImport } from './routes/_authenticated/_app.imports'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/_app.documents'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppChecklistTemplatesRouteImport } from './routes/_authenticated/_app.checklist-templates'
import { Route as AuthenticatedAppCertificatesRouteImport } from './routes/_authenticated/_app.certificates'
import { Route as AuthenticatedAppCertificateTemplatesRouteImport } from './routes/_authenticated/_app.certificate-templates'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/_app.assets'
import { Route as AuthenticatedAppAssetTypesRouteImport } from './routes/_authenticated/_app.asset-types'
import { Route as AuthenticatedAppMaintenanceIndexRouteImport } from './routes/_authenticated/_app.maintenance.index'
import { Route as AuthenticatedAppMaintenancePlansIndexRouteImport } from './routes/_authenticated/_app.maintenance-plans.index'
import { Route as AuthenticatedAppIncidentsIndexRouteImport } from './routes/_authenticated/_app.incidents.index'
import { Route as AuthenticatedAppChecklistTemplatesIndexRouteImport } from './routes/_authenticated/_app.checklist-templates.index'
import { Route as AuthenticatedAppCertificatesIndexRouteImport } from './routes/_authenticated/_app.certificates.index'
import { Route as AuthenticatedAppCertificateTemplatesIndexRouteImport } from './routes/_authenticated/_app.certificate-templates.index'
import { Route as AuthenticatedAppAssetsIndexRouteImport } from './routes/_authenticated/_app.assets.index'
import { Route as ApiPublicQrTokenRouteImport } from './routes/api/public/qr.$token'
import { Route as AuthenticatedAppMaintenanceIdRouteImport } from './routes/_authenticated/_app.maintenance.$id'
import { Route as AuthenticatedAppMaintenancePlansIdRouteImport } from './routes/_authenticated/_app.maintenance-plans.$id'
import { Route as AuthenticatedAppIncidentsIdRouteImport } from './routes/_authenticated/_app.incidents.$id'
import { Route as AuthenticatedAppChecklistTemplatesIdRouteImport } from './routes/_authenticated/_app.checklist-templates.$id'
import { Route as AuthenticatedAppCertificatesIdRouteImport } from './routes/_authenticated/_app.certificates.$id'
import { Route as AuthenticatedAppAssetsIdRouteImport } from './routes/_authenticated/_app.assets.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTokenRoute = QrTokenRouteImport.update({
  id: '/qr/$token',
  path: '/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectCompanyRoute =
  AuthenticatedSelectCompanyRouteImport.update({
    id: '/select-company',
    path: '/select-company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingCompanyRoute =
  AuthenticatedOnboardingCompanyRouteImport.update({
    id: '/onboarding/company',
    path: '/onboarding/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMaintenancePlansRoute =
  AuthenticatedAppMaintenancePlansRouteImport.update({
    id: '/maintenance-plans',
    path: '/maintenance-plans',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLocationsRoute =
  AuthenticatedAppLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIncidentsRoute =
  AuthenticatedAppIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportsRoute = AuthenticatedAppImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChecklistTemplatesRoute =
  AuthenticatedAppChecklistTemplatesRouteImport.update({
    id: '/checklist-templates',
    path: '/checklist-templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCertificatesRoute =
  AuthenticatedAppCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCertificateTemplatesRoute =
  AuthenticatedAppCertificateTemplatesRouteImport.update({
    id: '/certificate-templates',
    path: '/certificate-templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssetTypesRoute =
  AuthenticatedAppAssetTypesRouteImport.update({
    id: '/asset-types',
    path: '/asset-types',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMaintenanceIndexRoute =
  AuthenticatedAppMaintenanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMaintenanceRoute,
  } as any)
const AuthenticatedAppMaintenancePlansIndexRoute =
  AuthenticatedAppMaintenancePlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMaintenancePlansRoute,
  } as any)
const AuthenticatedAppIncidentsIndexRoute =
  AuthenticatedAppIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppIncidentsRoute,
  } as any)
const AuthenticatedAppChecklistTemplatesIndexRoute =
  AuthenticatedAppChecklistTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChecklistTemplatesRoute,
  } as any)
const AuthenticatedAppCertificatesIndexRoute =
  AuthenticatedAppCertificatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCertificatesRoute,
  } as any)
const AuthenticatedAppCertificateTemplatesIndexRoute =
  AuthenticatedAppCertificateTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCertificateTemplatesRoute,
  } as any)
const AuthenticatedAppAssetsIndexRoute =
  AuthenticatedAppAssetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAssetsRoute,
  } as any)
const ApiPublicQrTokenRoute = ApiPublicQrTokenRouteImport.update({
  id: '/api/public/qr/$token',
  path: '/api/public/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppMaintenanceIdRoute =
  AuthenticatedAppMaintenanceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMaintenanceRoute,
  } as any)
const AuthenticatedAppMaintenancePlansIdRoute =
  AuthenticatedAppMaintenancePlansIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMaintenancePlansRoute,
  } as any)
const AuthenticatedAppIncidentsIdRoute =
  AuthenticatedAppIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppIncidentsRoute,
  } as any)
const AuthenticatedAppChecklistTemplatesIdRoute =
  AuthenticatedAppChecklistTemplatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppChecklistTemplatesRoute,
  } as any)
const AuthenticatedAppCertificatesIdRoute =
  AuthenticatedAppCertificatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppCertificatesRoute,
  } as any)
const AuthenticatedAppAssetsIdRoute =
  AuthenticatedAppAssetsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/select-company': typeof AuthenticatedSelectCompanyRoute
  '/qr/$token': typeof QrTokenRoute
  '/asset-types': typeof AuthenticatedAppAssetTypesRoute
  '/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/certificate-templates': typeof AuthenticatedAppCertificateTemplatesRouteWithChildren
  '/certificates': typeof AuthenticatedAppCertificatesRouteWithChildren
  '/checklist-templates': typeof AuthenticatedAppChecklistTemplatesRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/imports': typeof AuthenticatedAppImportsRoute
  '/incidents': typeof AuthenticatedAppIncidentsRouteWithChildren
  '/locations': typeof AuthenticatedAppLocationsRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceRouteWithChildren
  '/maintenance-plans': typeof AuthenticatedAppMaintenancePlansRouteWithChildren
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/certificates/$id': typeof AuthenticatedAppCertificatesIdRoute
  '/checklist-templates/$id': typeof AuthenticatedAppChecklistTemplatesIdRoute
  '/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/maintenance-plans/$id': typeof AuthenticatedAppMaintenancePlansIdRoute
  '/maintenance/$id': typeof AuthenticatedAppMaintenanceIdRoute
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/assets/': typeof AuthenticatedAppAssetsIndexRoute
  '/certificate-templates/': typeof AuthenticatedAppCertificateTemplatesIndexRoute
  '/certificates/': typeof AuthenticatedAppCertificatesIndexRoute
  '/checklist-templates/': typeof AuthenticatedAppChecklistTemplatesIndexRoute
  '/incidents/': typeof AuthenticatedAppIncidentsIndexRoute
  '/maintenance-plans/': typeof AuthenticatedAppMaintenancePlansIndexRoute
  '/maintenance/': typeof AuthenticatedAppMaintenanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/select-company': typeof AuthenticatedSelectCompanyRoute
  '/qr/$token': typeof QrTokenRoute
  '/asset-types': typeof AuthenticatedAppAssetTypesRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/imports': typeof AuthenticatedAppImportsRoute
  '/locations': typeof AuthenticatedAppLocationsRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/certificates/$id': typeof AuthenticatedAppCertificatesIdRoute
  '/checklist-templates/$id': typeof AuthenticatedAppChecklistTemplatesIdRoute
  '/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/maintenance-plans/$id': typeof AuthenticatedAppMaintenancePlansIdRoute
  '/maintenance/$id': typeof AuthenticatedAppMaintenanceIdRoute
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/assets': typeof AuthenticatedAppAssetsIndexRoute
  '/certificate-templates': typeof AuthenticatedAppCertificateTemplatesIndexRoute
  '/certificates': typeof AuthenticatedAppCertificatesIndexRoute
  '/checklist-templates': typeof AuthenticatedAppChecklistTemplatesIndexRoute
  '/incidents': typeof AuthenticatedAppIncidentsIndexRoute
  '/maintenance-plans': typeof AuthenticatedAppMaintenancePlansIndexRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/select-company': typeof AuthenticatedSelectCompanyRoute
  '/qr/$token': typeof QrTokenRoute
  '/_authenticated/_app/asset-types': typeof AuthenticatedAppAssetTypesRoute
  '/_authenticated/_app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/_authenticated/_app/certificate-templates': typeof AuthenticatedAppCertificateTemplatesRouteWithChildren
  '/_authenticated/_app/certificates': typeof AuthenticatedAppCertificatesRouteWithChildren
  '/_authenticated/_app/checklist-templates': typeof AuthenticatedAppChecklistTemplatesRouteWithChildren
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/_app/imports': typeof AuthenticatedAppImportsRoute
  '/_authenticated/_app/incidents': typeof AuthenticatedAppIncidentsRouteWithChildren
  '/_authenticated/_app/locations': typeof AuthenticatedAppLocationsRoute
  '/_authenticated/_app/maintenance': typeof AuthenticatedAppMaintenanceRouteWithChildren
  '/_authenticated/_app/maintenance-plans': typeof AuthenticatedAppMaintenancePlansRouteWithChildren
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/_authenticated/_app/assets/$id': typeof AuthenticatedAppAssetsIdRoute
  '/_authenticated/_app/certificates/$id': typeof AuthenticatedAppCertificatesIdRoute
  '/_authenticated/_app/checklist-templates/$id': typeof AuthenticatedAppChecklistTemplatesIdRoute
  '/_authenticated/_app/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/_authenticated/_app/maintenance-plans/$id': typeof AuthenticatedAppMaintenancePlansIdRoute
  '/_authenticated/_app/maintenance/$id': typeof AuthenticatedAppMaintenanceIdRoute
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/_authenticated/_app/assets/': typeof AuthenticatedAppAssetsIndexRoute
  '/_authenticated/_app/certificate-templates/': typeof AuthenticatedAppCertificateTemplatesIndexRoute
  '/_authenticated/_app/certificates/': typeof AuthenticatedAppCertificatesIndexRoute
  '/_authenticated/_app/checklist-templates/': typeof AuthenticatedAppChecklistTemplatesIndexRoute
  '/_authenticated/_app/incidents/': typeof AuthenticatedAppIncidentsIndexRoute
  '/_authenticated/_app/maintenance-plans/': typeof AuthenticatedAppMaintenancePlansIndexRoute
  '/_authenticated/_app/maintenance/': typeof AuthenticatedAppMaintenanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/select-company'
    | '/qr/$token'
    | '/asset-types'
    | '/assets'
    | '/certificate-templates'
    | '/certificates'
    | '/checklist-templates'
    | '/dashboard'
    | '/documents'
    | '/imports'
    | '/incidents'
    | '/locations'
    | '/maintenance'
    | '/maintenance-plans'
    | '/notifications'
    | '/settings'
    | '/onboarding/company'
    | '/assets/$id'
    | '/certificates/$id'
    | '/checklist-templates/$id'
    | '/incidents/$id'
    | '/maintenance-plans/$id'
    | '/maintenance/$id'
    | '/api/public/qr/$token'
    | '/assets/'
    | '/certificate-templates/'
    | '/certificates/'
    | '/checklist-templates/'
    | '/incidents/'
    | '/maintenance-plans/'
    | '/maintenance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/select-company'
    | '/qr/$token'
    | '/asset-types'
    | '/dashboard'
    | '/documents'
    | '/imports'
    | '/locations'
    | '/notifications'
    | '/settings'
    | '/onboarding/company'
    | '/assets/$id'
    | '/certificates/$id'
    | '/checklist-templates/$id'
    | '/incidents/$id'
    | '/maintenance-plans/$id'
    | '/maintenance/$id'
    | '/api/public/qr/$token'
    | '/assets'
    | '/certificate-templates'
    | '/certificates'
    | '/checklist-templates'
    | '/incidents'
    | '/maintenance-plans'
    | '/maintenance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_app'
    | '/_authenticated/select-company'
    | '/qr/$token'
    | '/_authenticated/_app/asset-types'
    | '/_authenticated/_app/assets'
    | '/_authenticated/_app/certificate-templates'
    | '/_authenticated/_app/certificates'
    | '/_authenticated/_app/checklist-templates'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/documents'
    | '/_authenticated/_app/imports'
    | '/_authenticated/_app/incidents'
    | '/_authenticated/_app/locations'
    | '/_authenticated/_app/maintenance'
    | '/_authenticated/_app/maintenance-plans'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/settings'
    | '/_authenticated/onboarding/company'
    | '/_authenticated/_app/assets/$id'
    | '/_authenticated/_app/certificates/$id'
    | '/_authenticated/_app/checklist-templates/$id'
    | '/_authenticated/_app/incidents/$id'
    | '/_authenticated/_app/maintenance-plans/$id'
    | '/_authenticated/_app/maintenance/$id'
    | '/api/public/qr/$token'
    | '/_authenticated/_app/assets/'
    | '/_authenticated/_app/certificate-templates/'
    | '/_authenticated/_app/certificates/'
    | '/_authenticated/_app/checklist-templates/'
    | '/_authenticated/_app/incidents/'
    | '/_authenticated/_app/maintenance-plans/'
    | '/_authenticated/_app/maintenance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  QrTokenRoute: typeof QrTokenRoute
  ApiPublicQrTokenRoute: typeof ApiPublicQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$token': {
      id: '/qr/$token'
      path: '/qr/$token'
      fullPath: '/qr/$token'
      preLoaderRoute: typeof QrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-company': {
      id: '/_authenticated/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof AuthenticatedSelectCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/company': {
      id: '/_authenticated/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof AuthenticatedOnboardingCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/maintenance-plans': {
      id: '/_authenticated/_app/maintenance-plans'
      path: '/maintenance-plans'
      fullPath: '/maintenance-plans'
      preLoaderRoute: typeof AuthenticatedAppMaintenancePlansRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/maintenance': {
      id: '/_authenticated/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/locations': {
      id: '/_authenticated/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedAppLocationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/incidents': {
      id: '/_authenticated/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedAppIncidentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/imports': {
      id: '/_authenticated/_app/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedAppImportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/documents': {
      id: '/_authenticated/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/checklist-templates': {
      id: '/_authenticated/_app/checklist-templates'
      path: '/checklist-templates'
      fullPath: '/checklist-templates'
      preLoaderRoute: typeof AuthenticatedAppChecklistTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/certificates': {
      id: '/_authenticated/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedAppCertificatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/certificate-templates': {
      id: '/_authenticated/_app/certificate-templates'
      path: '/certificate-templates'
      fullPath: '/certificate-templates'
      preLoaderRoute: typeof AuthenticatedAppCertificateTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/assets': {
      id: '/_authenticated/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/asset-types': {
      id: '/_authenticated/_app/asset-types'
      path: '/asset-types'
      fullPath: '/asset-types'
      preLoaderRoute: typeof AuthenticatedAppAssetTypesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/maintenance/': {
      id: '/_authenticated/_app/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedAppMaintenanceRoute
    }
    '/_authenticated/_app/maintenance-plans/': {
      id: '/_authenticated/_app/maintenance-plans/'
      path: '/'
      fullPath: '/maintenance-plans/'
      preLoaderRoute: typeof AuthenticatedAppMaintenancePlansIndexRouteImport
      parentRoute: typeof AuthenticatedAppMaintenancePlansRoute
    }
    '/_authenticated/_app/incidents/': {
      id: '/_authenticated/_app/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedAppIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppIncidentsRoute
    }
    '/_authenticated/_app/checklist-templates/': {
      id: '/_authenticated/_app/checklist-templates/'
      path: '/'
      fullPath: '/checklist-templates/'
      preLoaderRoute: typeof AuthenticatedAppChecklistTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAppChecklistTemplatesRoute
    }
    '/_authenticated/_app/certificates/': {
      id: '/_authenticated/_app/certificates/'
      path: '/'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthenticatedAppCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCertificatesRoute
    }
    '/_authenticated/_app/certificate-templates/': {
      id: '/_authenticated/_app/certificate-templates/'
      path: '/'
      fullPath: '/certificate-templates/'
      preLoaderRoute: typeof AuthenticatedAppCertificateTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCertificateTemplatesRoute
    }
    '/_authenticated/_app/assets/': {
      id: '/_authenticated/_app/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAppAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAssetsRoute
    }
    '/api/public/qr/$token': {
      id: '/api/public/qr/$token'
      path: '/api/public/qr/$token'
      fullPath: '/api/public/qr/$token'
      preLoaderRoute: typeof ApiPublicQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/maintenance/$id': {
      id: '/_authenticated/_app/maintenance/$id'
      path: '/$id'
      fullPath: '/maintenance/$id'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceIdRouteImport
      parentRoute: typeof AuthenticatedAppMaintenanceRoute
    }
    '/_authenticated/_app/maintenance-plans/$id': {
      id: '/_authenticated/_app/maintenance-plans/$id'
      path: '/$id'
      fullPath: '/maintenance-plans/$id'
      preLoaderRoute: typeof AuthenticatedAppMaintenancePlansIdRouteImport
      parentRoute: typeof AuthenticatedAppMaintenancePlansRoute
    }
    '/_authenticated/_app/incidents/$id': {
      id: '/_authenticated/_app/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedAppIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedAppIncidentsRoute
    }
    '/_authenticated/_app/checklist-templates/$id': {
      id: '/_authenticated/_app/checklist-templates/$id'
      path: '/$id'
      fullPath: '/checklist-templates/$id'
      preLoaderRoute: typeof AuthenticatedAppChecklistTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedAppChecklistTemplatesRoute
    }
    '/_authenticated/_app/certificates/$id': {
      id: '/_authenticated/_app/certificates/$id'
      path: '/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof AuthenticatedAppCertificatesIdRouteImport
      parentRoute: typeof AuthenticatedAppCertificatesRoute
    }
    '/_authenticated/_app/assets/$id': {
      id: '/_authenticated/_app/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAppAssetsIdRouteImport
      parentRoute: typeof AuthenticatedAppAssetsRoute
    }
  }
}

interface AuthenticatedAppAssetsRouteChildren {
  AuthenticatedAppAssetsIdRoute: typeof AuthenticatedAppAssetsIdRoute
  AuthenticatedAppAssetsIndexRoute: typeof AuthenticatedAppAssetsIndexRoute
}

const AuthenticatedAppAssetsRouteChildren: AuthenticatedAppAssetsRouteChildren =
  {
    AuthenticatedAppAssetsIdRoute: AuthenticatedAppAssetsIdRoute,
    AuthenticatedAppAssetsIndexRoute: AuthenticatedAppAssetsIndexRoute,
  }

const AuthenticatedAppAssetsRouteWithChildren =
  AuthenticatedAppAssetsRoute._addFileChildren(
    AuthenticatedAppAssetsRouteChildren,
  )

interface AuthenticatedAppCertificateTemplatesRouteChildren {
  AuthenticatedAppCertificateTemplatesIndexRoute: typeof AuthenticatedAppCertificateTemplatesIndexRoute
}

const AuthenticatedAppCertificateTemplatesRouteChildren: AuthenticatedAppCertificateTemplatesRouteChildren =
  {
    AuthenticatedAppCertificateTemplatesIndexRoute:
      AuthenticatedAppCertificateTemplatesIndexRoute,
  }

const AuthenticatedAppCertificateTemplatesRouteWithChildren =
  AuthenticatedAppCertificateTemplatesRoute._addFileChildren(
    AuthenticatedAppCertificateTemplatesRouteChildren,
  )

interface AuthenticatedAppCertificatesRouteChildren {
  AuthenticatedAppCertificatesIdRoute: typeof AuthenticatedAppCertificatesIdRoute
  AuthenticatedAppCertificatesIndexRoute: typeof AuthenticatedAppCertificatesIndexRoute
}

const AuthenticatedAppCertificatesRouteChildren: AuthenticatedAppCertificatesRouteChildren =
  {
    AuthenticatedAppCertificatesIdRoute: AuthenticatedAppCertificatesIdRoute,
    AuthenticatedAppCertificatesIndexRoute:
      AuthenticatedAppCertificatesIndexRoute,
  }

const AuthenticatedAppCertificatesRouteWithChildren =
  AuthenticatedAppCertificatesRoute._addFileChildren(
    AuthenticatedAppCertificatesRouteChildren,
  )

interface AuthenticatedAppChecklistTemplatesRouteChildren {
  AuthenticatedAppChecklistTemplatesIdRoute: typeof AuthenticatedAppChecklistTemplatesIdRoute
  AuthenticatedAppChecklistTemplatesIndexRoute: typeof AuthenticatedAppChecklistTemplatesIndexRoute
}

const AuthenticatedAppChecklistTemplatesRouteChildren: AuthenticatedAppChecklistTemplatesRouteChildren =
  {
    AuthenticatedAppChecklistTemplatesIdRoute:
      AuthenticatedAppChecklistTemplatesIdRoute,
    AuthenticatedAppChecklistTemplatesIndexRoute:
      AuthenticatedAppChecklistTemplatesIndexRoute,
  }

const AuthenticatedAppChecklistTemplatesRouteWithChildren =
  AuthenticatedAppChecklistTemplatesRoute._addFileChildren(
    AuthenticatedAppChecklistTemplatesRouteChildren,
  )

interface AuthenticatedAppIncidentsRouteChildren {
  AuthenticatedAppIncidentsIdRoute: typeof AuthenticatedAppIncidentsIdRoute
  AuthenticatedAppIncidentsIndexRoute: typeof AuthenticatedAppIncidentsIndexRoute
}

const AuthenticatedAppIncidentsRouteChildren: AuthenticatedAppIncidentsRouteChildren =
  {
    AuthenticatedAppIncidentsIdRoute: AuthenticatedAppIncidentsIdRoute,
    AuthenticatedAppIncidentsIndexRoute: AuthenticatedAppIncidentsIndexRoute,
  }

const AuthenticatedAppIncidentsRouteWithChildren =
  AuthenticatedAppIncidentsRoute._addFileChildren(
    AuthenticatedAppIncidentsRouteChildren,
  )

interface AuthenticatedAppMaintenanceRouteChildren {
  AuthenticatedAppMaintenanceIdRoute: typeof AuthenticatedAppMaintenanceIdRoute
  AuthenticatedAppMaintenanceIndexRoute: typeof AuthenticatedAppMaintenanceIndexRoute
}

const AuthenticatedAppMaintenanceRouteChildren: AuthenticatedAppMaintenanceRouteChildren =
  {
    AuthenticatedAppMaintenanceIdRoute: AuthenticatedAppMaintenanceIdRoute,
    AuthenticatedAppMaintenanceIndexRoute:
      AuthenticatedAppMaintenanceIndexRoute,
  }

const AuthenticatedAppMaintenanceRouteWithChildren =
  AuthenticatedAppMaintenanceRoute._addFileChildren(
    AuthenticatedAppMaintenanceRouteChildren,
  )

interface AuthenticatedAppMaintenancePlansRouteChildren {
  AuthenticatedAppMaintenancePlansIdRoute: typeof AuthenticatedAppMaintenancePlansIdRoute
  AuthenticatedAppMaintenancePlansIndexRoute: typeof AuthenticatedAppMaintenancePlansIndexRoute
}

const AuthenticatedAppMaintenancePlansRouteChildren: AuthenticatedAppMaintenancePlansRouteChildren =
  {
    AuthenticatedAppMaintenancePlansIdRoute:
      AuthenticatedAppMaintenancePlansIdRoute,
    AuthenticatedAppMaintenancePlansIndexRoute:
      AuthenticatedAppMaintenancePlansIndexRoute,
  }

const AuthenticatedAppMaintenancePlansRouteWithChildren =
  AuthenticatedAppMaintenancePlansRoute._addFileChildren(
    AuthenticatedAppMaintenancePlansRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssetTypesRoute: typeof AuthenticatedAppAssetTypesRoute
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRouteWithChildren
  AuthenticatedAppCertificateTemplatesRoute: typeof AuthenticatedAppCertificateTemplatesRouteWithChildren
  AuthenticatedAppCertificatesRoute: typeof AuthenticatedAppCertificatesRouteWithChildren
  AuthenticatedAppChecklistTemplatesRoute: typeof AuthenticatedAppChecklistTemplatesRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppImportsRoute: typeof AuthenticatedAppImportsRoute
  AuthenticatedAppIncidentsRoute: typeof AuthenticatedAppIncidentsRouteWithChildren
  AuthenticatedAppLocationsRoute: typeof AuthenticatedAppLocationsRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRouteWithChildren
  AuthenticatedAppMaintenancePlansRoute: typeof AuthenticatedAppMaintenancePlansRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssetTypesRoute: AuthenticatedAppAssetTypesRoute,
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRouteWithChildren,
  AuthenticatedAppCertificateTemplatesRoute:
    AuthenticatedAppCertificateTemplatesRouteWithChildren,
  AuthenticatedAppCertificatesRoute:
    AuthenticatedAppCertificatesRouteWithChildren,
  AuthenticatedAppChecklistTemplatesRoute:
    AuthenticatedAppChecklistTemplatesRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppImportsRoute: AuthenticatedAppImportsRoute,
  AuthenticatedAppIncidentsRoute: AuthenticatedAppIncidentsRouteWithChildren,
  AuthenticatedAppLocationsRoute: AuthenticatedAppLocationsRoute,
  AuthenticatedAppMaintenanceRoute:
    AuthenticatedAppMaintenanceRouteWithChildren,
  AuthenticatedAppMaintenancePlansRoute:
    AuthenticatedAppMaintenancePlansRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedSelectCompanyRoute: typeof AuthenticatedSelectCompanyRoute
  AuthenticatedOnboardingCompanyRoute: typeof AuthenticatedOnboardingCompanyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedSelectCompanyRoute: AuthenticatedSelectCompanyRoute,
  AuthenticatedOnboardingCompanyRoute: AuthenticatedOnboardingCompanyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  QrTokenRoute: QrTokenRoute,
  ApiPublicQrTokenRoute: ApiPublicQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
