/**
 * Catalogue of every data operation of the maintenance module, kept in sync with contracts/repositories.ts
 * by contracts/__tests__/operations.test.ts. `authority` names the PostgreSQL object (sql/install_v1.sql)
 * or host port that decides; TypeScript checks are UX only.
 */
export type OperationKind = "read" | "write" | "atomic" | "host";
export type HostDependency = "sites" | "people" | "documents" | "storage";
export type OperationSpec = {
  kind: OperationKind;
  /** Permission the database enforces (null = pure utility). */
  perm: string | null;
  authority: string;
  host: readonly HostDependency[];
  /** false only for operations acting on an already org-scoped path/token. */
  orgScoped: boolean;
};

export const OPERATIONS = {
  "assets.listFamilies": { kind: "read", perm: "mnt.view", authority: "RLS mnt_asset_families (globales + org)", host: [], orgScoped: true },
  "assets.createFamily": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_asset_families", host: [], orgScoped: true },
  "assets.setFamilyRequiresCertificate": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_asset_families (is_system inmutable)", host: [], orgScoped: true },
  "assets.deleteFamily": { kind: "write", perm: "mnt.admin", authority: "RLS; FK compuesta impide borrar familias en uso", host: [], orgScoped: true },
  "assets.listTypes": { kind: "read", perm: "mnt.view", authority: "RLS + mnt_org_asset_types (solo activados)", host: [], orgScoped: true },
  "assets.listTypesAdmin": { kind: "read", perm: "mnt.admin", authority: "RLS mnt_asset_types + activación", host: [], orgScoped: true },
  "assets.createType": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_asset_types", host: [], orgScoped: true },
  "assets.setTypeFamily": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_asset_types", host: [], orgScoped: true },
  "assets.deleteType": { kind: "write", perm: "mnt.admin", authority: "RLS; FK compuesta", host: [], orgScoped: true },
  "assets.listActiveSites": { kind: "host", perm: "mnt.view", authority: "SitePort.tree del host", host: ["sites"], orgScoped: true },
  "assets.listScopeSites": { kind: "host", perm: "mnt.view", authority: "SitePort.tree del host (jerarquía)", host: ["sites"], orgScoped: true },
  "assets.listSites": { kind: "host", perm: "mnt.view", authority: "SitePort.tree del host", host: ["sites"], orgScoped: true },
  "assets.listAssets": { kind: "read", perm: "mnt.view", authority: "RLS mnt_assets", host: ["sites"], orgScoped: true },
  "assets.getAsset": { kind: "read", perm: "mnt.view", authority: "RLS mnt_assets", host: ["sites"], orgScoped: true },
  "assets.createAsset": { kind: "write", perm: "mnt.manage_assets", authority: "RLS + triggers mnt_tg_site_scope / mnt_type_usable + código mnt_next_code", host: ["sites"], orgScoped: true },
  "assets.updateAsset": { kind: "write", perm: "mnt.manage_assets", authority: "RLS + trigger mnt_tg_site_scope", host: ["sites"], orgScoped: true },
  "assets.softDeleteAsset": { kind: "write", perm: "mnt.manage_assets", authority: "RLS mnt_assets (deleted_at)", host: [], orgScoped: true },
  "assets.listKitItems": { kind: "read", perm: "mnt.view", authority: "RLS mnt_kit_items", host: [], orgScoped: true },
  "assets.saveKitItem": { kind: "write", perm: "mnt.manage_assets", authority: "RLS mnt_kit_items (FK compuesta org,asset)", host: [], orgScoped: true },
  "assets.insertKitItems": { kind: "write", perm: "mnt.manage_assets", authority: "RLS mnt_kit_items", host: [], orgScoped: true },
  "assets.deleteKitItem": { kind: "write", perm: "mnt.manage_assets", authority: "RLS mnt_kit_items", host: [], orgScoped: true },
  "checklists.listTemplates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_templates + puentes _types/_sites", host: [], orgScoped: true },
  "checklists.getTemplate": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_templates", host: [], orgScoped: true },
  "checklists.getTemplateScope": { kind: "read", perm: "mnt.view", authority: "RLS puentes _types/_sites", host: [], orgScoped: true },
  "checklists.createTemplate": { kind: "write", perm: "mnt.admin", authority: "RLS + puentes (FK compuestas)", host: ["sites"], orgScoped: true },
  "checklists.updateTemplateScope": { kind: "write", perm: "mnt.admin", authority: "RLS puentes; sustitución en una transacción", host: ["sites"], orgScoped: true },
  "checklists.listPublishedTemplates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_versions (publicadas)", host: [], orgScoped: true },
  "checklists.listVersions": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_versions", host: [], orgScoped: true },
  "checklists.latestPublishedVersions": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_versions", host: [], orgScoped: true },
  "checklists.publishVersion": { kind: "atomic", perm: "mnt.admin", authority: "RPC mnt_publish_checklist_version", host: [], orgScoped: true },
  "checklists.createVersion": { kind: "write", perm: "mnt.admin", authority: "RLS; clonado de preguntas en la misma transacción", host: [], orgScoped: true },
  "checklists.listQuestions": { kind: "read", perm: "mnt.view", authority: "RLS mnt_checklist_questions", host: [], orgScoped: true },
  "checklists.addQuestion": { kind: "write", perm: "mnt.admin", authority: "RLS + mnt_tg_checklist_guard (versión publicada inmutable)", host: [], orgScoped: true },
  "checklists.deleteQuestion": { kind: "write", perm: "mnt.admin", authority: "RLS + mnt_tg_checklist_guard", host: [], orgScoped: true },
  "checklists.listResponses": { kind: "read", perm: "mnt.view", authority: "RLS mnt_responses", host: [], orgScoped: true },
  "checklists.saveResponse": { kind: "write", perm: "mnt.run", authority: "RLS + mnt_tg_item_guard (sesión abierta)", host: ["people"], orgScoped: true },
  "plans.listPlans": { kind: "read", perm: "mnt.view", authority: "RLS mnt_plans", host: [], orgScoped: true },
  "plans.getPlan": { kind: "read", perm: "mnt.view", authority: "RLS mnt_plans", host: [], orgScoped: true },
  "plans.listPlanAssets": { kind: "read", perm: "mnt.view", authority: "RLS mnt_plan_assets", host: [], orgScoped: true },
  "plans.listCertificateTemplates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "plans.listScopeAssets": { kind: "read", perm: "mnt.view", authority: "RLS mnt_assets + expansión de centros", host: ["sites"], orgScoped: true },
  "plans.createPlan": { kind: "write", perm: "mnt.admin", authority: "RLS + puentes mnt_plan_sites/_assets/_type_templates", host: ["sites"], orgScoped: true },
  "plans.setCertificateTemplate": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_plans (FK compuesta)", host: [], orgScoped: true },
  "plans.setActive": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_plans", host: [], orgScoped: true },
  "plans.addAssets": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_plan_assets (FK compuesta)", host: [], orgScoped: true },
  "plans.removeAsset": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_plan_assets", host: [], orgScoped: true },
  "sessions.listSessions": { kind: "read", perm: "mnt.view", authority: "RLS mnt_sessions", host: [], orgScoped: true },
  "sessions.getSession": { kind: "read", perm: "mnt.view", authority: "RLS mnt_sessions", host: ["people"], orgScoped: true },
  "sessions.listItems": { kind: "read", perm: "mnt.view", authority: "RLS mnt_session_items", host: [], orgScoped: true },
  "sessions.listPlansForSession": { kind: "read", perm: "mnt.run", authority: "RLS mnt_plans", host: [], orgScoped: true },
  "sessions.listPlanLocations": { kind: "read", perm: "mnt.run", authority: "RLS mnt_plan_sites + SitePort", host: ["sites"], orgScoped: true },
  "sessions.listAssetHistory": { kind: "read", perm: "mnt.view", authority: "RLS mnt_session_items / mnt_session_history", host: [], orgScoped: true },
  "sessions.createSession": { kind: "atomic", perm: "mnt.run", authority: "RPC mnt_create_session (idempotente por request_id)", host: ["sites", "people"], orgScoped: true },
  "sessions.startSession": { kind: "write", perm: "mnt.run", authority: "RLS + mnt_tg_session_guard (draft→in_progress)", host: [], orgScoped: true },
  "sessions.assertItemWritable": { kind: "read", perm: "mnt.run", authority: "Solo UX: la autoridad es mnt_tg_item_guard", host: [], orgScoped: true },
  "sessions.setItemResult": { kind: "write", perm: "mnt.run", authority: "RLS + mnt_tg_item_guard", host: ["people"], orgScoped: true },
  "sessions.closeSession": { kind: "atomic", perm: "mnt.close", authority: "RPC mnt_close_session (snapshot + historial + outbox)", host: ["people"], orgScoped: true },
  "incidents.listIncidents": { kind: "read", perm: "mnt.view", authority: "RLS mnt_incidents", host: [], orgScoped: true },
  "incidents.getIncident": { kind: "read", perm: "mnt.view", authority: "RLS mnt_incidents", host: ["people"], orgScoped: true },
  "incidents.listHistory": { kind: "read", perm: "mnt.view", authority: "RLS mnt_incident_history (append-only)", host: ["people"], orgScoped: true },
  "incidents.listMembers": { kind: "host", perm: "mnt.view", authority: "PeoplePort.search del host", host: ["people"], orgScoped: true },
  "incidents.listAssetOptions": { kind: "read", perm: "mnt.view", authority: "RLS mnt_assets", host: [], orgScoped: true },
  "incidents.listAssetIncidents": { kind: "read", perm: "mnt.view", authority: "RLS mnt_incidents", host: [], orgScoped: true },
  "incidents.createManual": { kind: "atomic", perm: "mnt.run", authority: "RPC mnt_open_incident", host: ["people"], orgScoped: true },
  "incidents.update": { kind: "write", perm: "mnt.run", authority: "RLS mnt_incidents (el estado no cambia aquí)", host: ["people"], orgScoped: true },
  "incidents.changeStatus": { kind: "atomic", perm: "mnt.run", authority: "RPC mnt_change_incident_status (transiciones en PostgreSQL)", host: ["people"], orgScoped: true },
  "incidents.remove": { kind: "write", perm: "mnt.admin", authority: "RLS; solo sin historial (inmutabilidad)", host: [], orgScoped: true },
  "incidents.openForFailures": { kind: "atomic", perm: "mnt.run", authority: "RPC mnt_open_incident por fallo (o dentro de mnt_close_session)", host: ["people"], orgScoped: true },
  "certificates.resolveTemplate": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.listCertificates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificates", host: [], orgScoped: true },
  "certificates.getCertificate": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificates", host: [], orgScoped: true },
  "certificates.listItems": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_items", host: [], orgScoped: true },
  "certificates.listIncidents": { kind: "read", perm: "mnt.view", authority: "RLS mnt_incidents", host: [], orgScoped: true },
  "certificates.appliedTemplate": { kind: "read", perm: "mnt.view", authority: "Snapshot congelado en el certificado", host: [], orgScoped: true },
  "certificates.revoke": { kind: "atomic", perm: "mnt.certify", authority: "RPC mnt_revoke_certificate", host: [], orgScoped: true },
  "certificates.updateNotes": { kind: "write", perm: "mnt.certify", authority: "RLS + mnt_tg_certificate_guard (solo notas)", host: [], orgScoped: true },
  "certificates.listAssetCertificates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_items", host: [], orgScoped: true },
  "certificates.findSessionCertificate": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificates", host: [], orgScoped: true },
  "certificates.emitForSession": { kind: "atomic", perm: "mnt.certify", authority: "Transacción única (certificado + ítems + outbox); PDF después", host: ["people"], orgScoped: true },
  "certificates.loadPdfSource": { kind: "read", perm: "mnt.certify", authority: "RLS; datos congelados del certificado", host: [], orgScoped: true },
  "certificates.resolveTemplateForSession": { kind: "read", perm: "mnt.certify", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.readFrozenLogo": { kind: "host", perm: "mnt.certify", authority: "Almacenamiento del host (lectura de bytes)", host: ["storage"], orgScoped: true },
  "certificates.sha256Hex": { kind: "host", perm: null, authority: "Utilidad pura; el hash de autoridad lo recalcula el servidor", host: [], orgScoped: false },
  "certificates.signedLogoUrl": { kind: "host", perm: "mnt.view", authority: "Almacenamiento del host (URL firmada)", host: ["storage"], orgScoped: false },
  "certificates.storePdf": { kind: "atomic", perm: "mnt.certify", authority: "DocumentPort.registerVersion + RPC mnt_attach_certificate_pdf (SHA debe coincidir)", host: ["documents", "storage"], orgScoped: true },
  "certificates.pdfDownloadUrl": { kind: "host", perm: "mnt.view", authority: "DocumentPort.signedUrl", host: ["documents"], orgScoped: true },
  "certificates.listTemplates": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.getTemplate": { kind: "read", perm: "mnt.view", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.createTemplate": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.updateTemplate": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.softDeleteTemplate": { kind: "write", perm: "mnt.admin", authority: "RLS mnt_certificate_templates", host: [], orgScoped: true },
  "certificates.uploadTemplateLogo": { kind: "host", perm: "mnt.admin", authority: "Almacenamiento del host (bytes Uint8Array)", host: ["storage"], orgScoped: true },
  "certificates.listAssetsForExternal": { kind: "read", perm: "mnt.certify", authority: "RLS mnt_assets", host: [], orgScoped: true },
  "certificates.registerExternal": { kind: "atomic", perm: "mnt.certify", authority: "RPC mnt_register_external_certificate", host: ["documents", "people"], orgScoped: true },
} as const satisfies Record<string, OperationSpec>;

export type OperationKey = keyof typeof OPERATIONS;
